"Filed out from Dolphin Smalltalk"!

SBSCDNDeploymentLibrary subclass: #SBSIconsCDNDeploymentLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSIconsCDNDeploymentLibrary guid: (GUID fromString: '{e64fe9d4-fb60-483e-bb67-c26aeb0b555e}')!

SBSIconsCDNDeploymentLibrary comment: ''!

!SBSIconsCDNDeploymentLibrary categoriesForClass!Libraries! !

!SBSIconsCDNDeploymentLibrary class methodsFor!

addLoadScriptTo: html	"No load script for icons"!

cdnCSSLocation	^'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css'!

cdnCSSLocationIntegrity	"Calculated via https://www.srihash.org"	^ 'sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD'! !

!SBSIconsCDNDeploymentLibrary class categoriesForMethods!
addLoadScriptTo:!public!updating! !
cdnCSSLocation!accessing / defaults!public! !
cdnCSSLocationIntegrity!accessing / defaults!public! !
!

