"Filed out from Dolphin Smalltalk"!

SBSCDNDeploymentLibrary subclass: #SBSJQueryCDNDeploymentLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSJQueryCDNDeploymentLibrary guid: (GUID fromString: '{13c49c5c-400a-43a6-89ac-d07afdf990df}')!

SBSJQueryCDNDeploymentLibrary comment: ''!

!SBSJQueryCDNDeploymentLibrary categoriesForClass!Unclassified! !

!SBSJQueryCDNDeploymentLibrary class methodsFor!

cdnJSLocation	^'https://cdn.jsdelivr.net/npm/jquery@4.0.0/dist/jquery.min.js'!

cdnJSLocationIntegrity	"Calculated via https://www.srihash.org"	^ 'sha384-fgGyf7Mo7DURSOMnOy7ed+dkq5Job205Gnzu6QIg0BOHKaqt4D76Dt8VlDCzcMHV'! !

!SBSJQueryCDNDeploymentLibrary class categoriesForMethods!
cdnJSLocation!accessing / defaults!public! !
cdnJSLocationIntegrity!accessing / defaults!public! !
!

