"Filed out from Dolphin Smalltalk"!

SBSCDNDeploymentLibrary subclass: #SBSJQueryCDNDeploymentLibrary
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SBSJQueryCDNDeploymentLibrary guid: (GUID fromString: '{13c49c5c-400a-43a6-89ac-d07afdf990df}')!

SBSJQueryCDNDeploymentLibrary comment: ''!

!SBSJQueryCDNDeploymentLibrary categoriesForClass!Unclassified! !

!SBSJQueryCDNDeploymentLibrary class methodsFor!

cdnJSLocation	^'https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js'!

cdnJSLocationIntegrity	"Calculated via https://www.srihash.org"	^ 'sha384-1H217gwSVyLSIfaLxHbE7dRb3v4mYCKbpQvzx0cegeju1MVsGrX5xXxAvs/HgeFs'! !

!SBSJQueryCDNDeploymentLibrary class categoriesForMethods!
cdnJSLocation!accessing / defaults!public! !
cdnJSLocationIntegrity!accessing / defaults!public! !
!

